イベント開催会場を「株式会社インプレス」に更新
nakao-s23010/ichiyasaGitSample pull request #1
Opened 2024-06-06 05:25 UTC by nakao-s23010

2024-06-06 05:35 UTC, ichiyasa-s23018 reviewed
無修正ありがとうございます！問題ないのでマージするでござる

2024-06-06 05:35 UTC, ichiyasa-s23018 commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
修正ありがとうございます！問題ないのでマージするでござる

2024-06-12 02:33 UTC, nakao-s23010 reviewed
変更

2024-06-12 02:33 UTC, nakao-s23010 commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
変更変更変更

2024-06-12 02:36 UTC, yasuda-s23016 requested changes

2024-06-12 02:36 UTC, yasuda-s23016 commented on index.html
>                          <p>3月23日 19:00開始</p>
？？？？

2024-06-12 02:39 UTC, nakao-s23010 commented on index.html
>                          <p>3月23日 19:00開始</p>
！！！！！

2024-06-12 02:45 UTC, yasuda-s23016 approved these changes

2024-06-12 02:46 UTC, merged